### ISSUE TITLE
SkyFactory4 - bug visual craftertable

### ISSUE THREAD

**Issue by joaoespanhol** [wolflord212312/Server-Problems#2]
Bug visual
![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/56f5948e-4902-4ff2-a756-f0c7e1be4e68)

![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/df0273bd-afab-4f8a-aa61-bedbb1753e4b)

**Comment by wolflord212312** [comment]
I can not fix visual bugs as this would need to be fixed in the modpack itself
