### ISSUE TITLE
SkyFactory 4 void problem plugin

### ISSUE THREAD

**Issue by joaoespanhol** [wolflord212312/Server-Problems#3]
when void falls, it's always teleporting to the same place, you can't move, you have to give the command: is go

video bug: 
https://youtu.be/_fyBZJZP3o4

**Comment by wolflord212312** [comment]
This is default VoidProtect mod behaviour happens on solo already knew about it

**Comment by wolflord212312** [comment]
Will be fixed when i get time to do it today sometime

**Comment by joaoespanhol** [comment]
> Will be fixed when i get time to do it today sometime

your no fix problem
