### ISSUE TITLE
SkYFactory 4 problem vote

### ISSUE THREAD

**Issue by joaoespanhol** [wolflord212312/Server-Problems#4]
Hi,

Can't vote this website: https://www.minecraftiplist.com/server/FoxyCraftNetwork-24467

![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/a90ca807-e992-4cf9-8160-c2c9f051af7e)

**Comment by wolflord212312** [comment]
Ya gonna remove this one seems to be glitchy all the time and bad to use.
