### ISSUE TITLE
SkyFactory problem lang Plugin is

### ISSUE THREAD

**Issue by joaoespanhol** [wolflord212312/Server-Problems#6]
I changed the language from English to Portuguese, but not everything is completely in Portuguese

Exemple down
Is cp

![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/df52bb16-2495-4abd-b2e9-40dfe0dfc16a)

![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/bf98a012-0e1f-4240-8cb2-d57ebf578be2)

**Comment by wolflord212312** [comment]
Ok i can send you the lang file if you want to convert it?

**Comment by wolflord212312** [comment]
Please make a PR to fix https://github.com/wolflord212312/Server-Problems/blob/main/pt-BR.yml as it is not a language i can speak and it is also possible this plugin hard codes some stuff

**Comment by joaoespanhol** [comment]
i no find english langs @wolflord212312 

it's a plugin code problem, it shouldn't be calling that category, it can upload the english language to check if it's speaking something portuguese file
