### ISSUE TITLE
SkyFactory4 Warps shops

### ISSUE THREAD

**Issue by joaoespanhol** [wolflord212312/Server-Problems#7]
No working, i buy, is say no have money
![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/57109197-8876-426e-9556-96e7b9f77383)

![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/9f3af1e9-8e16-439b-baca-c4a821d633f8)

**Comment by wolflord212312** [comment]
Ok so money from crates is not giving you money?

**Comment by wolflord212312** [comment]
Ok crates should be fixed here soon i will give you 2 keys once i apply this fix
