### ISSUE TITLE
SkyFactory Tag

### ISSUE THREAD

**Issue by joaoespanhol** [wolflord212312/Server-Problems#8]
Say i no have tag
![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/da99c6d1-5a64-4c34-8b3d-706508b27d83)

https://media.discordapp.net/attachments/1051159974253953064/1137649556566311042/image.png?width=1439&height=350

i have win tag: chest vote O.o

**Comment by joaoespanhol** [comment]
info: /tags

![image](https://github.com/wolflord212312/Server-Problems/assets/22871432/5639b210-d7ea-46eb-a8e0-1d995934eb78)

**Comment by wolflord212312** [comment]
Will be fixed was a issue with crates
